export const OPS_MANUAL_SEED_SOURCE = 'codex_seed_20260704';

export const OPS_MANUAL_SEED_PAYLOAD = {
  source: OPS_MANUAL_SEED_SOURCE,
  status: 'seeded',
  schema_version: 1,
  seeded_at_ms: 1783123200000,
  updated_at_ms: 1783123200000,
  entries: [
    {
      id: 'seed_order_chicken_thigh_out_of_stock',
      category: 'order',
      title: '닭다리 품절 주문 처리',
      summary: '닭다리가 품절이면 재고 확인, 대체 가능 여부, 고객 안내 순서로 처리한다.',
      body: '- 주문 접수 전에 닭다리 재고를 먼저 확인한다.\n- 품절이면 대체 메뉴 가능 여부와 안내 문구를 분리한다.\n- 이미 들어온 주문은 임의 취소보다 고객 확인을 우선한다.',
      tags: ['order', 'safety', 'stock', 'customer'],
      search_text: '닭다리 품절 주문 처리 재고 대체 메뉴 고객 확인',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_order_chicken_thigh_out_of_stock'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123200000,
      updated_at_ms: 1783123200000,
      updated_at: '2026-07-04T00:00:00.000Z',
    },
    {
      id: 'seed_manual_input_principles',
      category: 'manual',
      title: '운영메뉴얼 입력 원칙',
      summary: '원문은 그대로 복붙하지 않고 판단 가능한 문장, 태그, 검색어를 같이 정리한다.',
      body: '- 원문을 한 줄로 붙여 넣지 말고 항목 단위로 정리한다.\n- category, tags, search_text, source, status, updated_at을 함께 적는다.\n- 입력 후에는 중복 주제와 보완 주제를 구분해서 편입한다.',
      tags: ['manual', 'input', 'search', 'source'],
      search_text: '운영메뉴얼 입력 원칙 원문 복붙 금지 category tags search_text source status updated_at',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_manual_input_principles'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123201000,
      updated_at_ms: 1783123201000,
      updated_at: '2026-07-04T00:00:01.000Z',
    },
    {
      id: 'seed_work_schedule_boundary',
      category: 'work',
      title: '근무표 원천/수정 기준',
      summary: '근무 원천은 WorkSchedule 데이터만 쓰고, 수정은 override와 status로 분리한다.',
      body: '- planned work는 /workschedule_v2를 단일 원천으로 본다.\n- 수정은 overrides에, 확정/메타는 status에 남긴다.\n- clear는 고정근무를 지우는 표식이지 삭제가 아니다.',
      tags: ['work', 'schedule', 'override', 'status'],
      search_text: '근무표 원천 수정 기준 workschedule_v2 overrides status clear 삭제 아님',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_work_schedule_boundary'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123202000,
      updated_at_ms: 1783123202000,
      updated_at: '2026-07-04T00:00:02.000Z',
    },
    {
      id: 'seed_discount_briefing_same_day',
      category: 'discount',
      title: '할인행사 당일 브리핑 기준',
      summary: '당일 할인행사는 대상, 예외, 종료 시각을 먼저 짧게 알린다.',
      body: '- 행사명만 적지 말고 적용 대상과 예외를 함께 적는다.\n- 당일 브리핑에는 종료 시각과 재안내 필요 여부를 넣는다.\n- 확인이 끝나지 않으면 확정 표현보다 보류 표현을 쓴다.',
      tags: ['discount', 'briefing', 'same_day', 'safety'],
      search_text: '할인행사 당일 브리핑 기준 대상 예외 종료 시각 보류',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_discount_briefing_same_day'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123203000,
      updated_at_ms: 1783123203000,
      updated_at: '2026-07-04T00:00:03.000Z',
    },
    {
      id: 'seed_delivery_lookup_rules',
      category: 'delivery',
      title: '배달정보 조회 기준',
      summary: '주소, 건물명, 호수, 비밀번호는 확인된 최신값만 짧게 쓴다.',
      body: '- 배달정보는 주소, 건물명, 호수, 비밀번호를 분리해서 확인한다.\n- group_only 표기는 필요한 정보가 따로 있다는 뜻으로 남긴다.\n- 불명확하면 추정하지 말고 확인 경로를 남긴다.',
      tags: ['delivery', 'address', 'password', 'group_only'],
      search_text: '배달정보 조회 기준 주소 건물명 호수 비밀번호 group_only 최신값',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_delivery_lookup_rules'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123204000,
      updated_at_ms: 1783123204000,
      updated_at: '2026-07-04T00:00:04.000Z',
    },
    {
      id: 'seed_task_alarm_rules',
      category: 'task',
      title: '할일/알람 등록 기준',
      summary: '할일과 알람은 마감 시각, 반복 여부, 담당자를 같이 적는다.',
      body: '- 할일은 해야 할 일과 실행 기한을 한 번에 보이게 쓴다.\n- 알람은 반복 여부와 알림 시각을 분리해서 적는다.\n- 실행 주체가 필요한 경우 담당자나 방식을 같이 적는다.',
      tags: ['task', 'alarm', 'todo', 'deadline'],
      search_text: '할일 알람 등록 기준 마감 반복 담당자 todo reminder',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_task_alarm_rules'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123205000,
      updated_at_ms: 1783123205000,
      updated_at: '2026-07-04T00:00:05.000Z',
    },
  ],
  memos: [],
};
