export const OPS_MANUAL_SEED_SOURCE = 'codex_seed_20260704';

export const OPS_MANUAL_SEED_PAYLOAD = {
  source: OPS_MANUAL_SEED_SOURCE,
  status: 'seeded',
  schema_version: 1,
  seeded_at_ms: 1783123200000,
  updated_at_ms: 1783123200000,
  entries: [
    {
      id: 'seed_manual_input_principles',
      category: 'manual',
      title: '운영메뉴얼 입력 원칙',
      summary: '원문은 그대로 복붙하지 않고 판단 가능한 문장, 태그, 검색어를 같이 정리한다.',
      body: '- 원문을 한 줄로 붙여 넣지 말고 항목 단위로 정리한다.\n- category, tags, search_text, source, status, updated_at을 함께 적는다.\n- 입력 후에는 중복 주제와 보완 주제를 구분해서 편입한다.',
      tags: ['manual', 'input', 'search', 'source'],
      search_text: '운영메뉴얼 입력 원칙 원문 복붙 금지 category tags search_text source status updated_at',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_manual_input_principles'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123201000,
      updated_at_ms: 1783123201000,
      updated_at: '2026-07-04T00:00:01.000Z',
    },
    {
      id: 'seed_work_schedule_boundary',
      category: 'work',
      title: '근무표 원천/수정 기준',
      summary: '근무 원천은 WorkSchedule 데이터만 쓰고, 수정은 override와 status로 분리한다.',
      body: '- planned work는 /workschedule_v2를 단일 원천으로 본다.\n- 수정은 overrides에, 확정/메타는 status에 남긴다.\n- clear는 고정근무를 지우는 표식이지 삭제가 아니다.',
      tags: ['work', 'schedule', 'override', 'status'],
      search_text: '근무표 원천 수정 기준 workschedule_v2 overrides status clear 삭제 아님',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_work_schedule_boundary'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123202000,
      updated_at_ms: 1783123202000,
      updated_at: '2026-07-04T00:00:02.000Z',
    },
    {
      id: 'seed_discount_briefing_same_day',
      category: 'discount',
      title: '할인행사 당일 브리핑 기준',
      summary: '당일 할인행사는 대상, 예외, 종료 시각을 먼저 짧게 알린다.',
      body: '- 행사명만 적지 말고 적용 대상과 예외를 함께 적는다.\n- 당일 브리핑에는 종료 시각과 재안내 필요 여부를 넣는다.\n- 확인이 끝나지 않으면 확정 표현보다 보류 표현을 쓴다.',
      tags: ['discount', 'briefing', 'same_day', 'safety'],
      search_text: '할인행사 당일 브리핑 기준 대상 예외 종료 시각 보류',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_discount_briefing_same_day'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123203000,
      updated_at_ms: 1783123203000,
      updated_at: '2026-07-04T00:00:03.000Z',
    },
    {
      id: 'seed_delivery_lookup_rules',
      category: 'delivery',
      title: '배달정보 조회 기준',
      summary: '주소, 건물명, 호수, 비밀번호는 확인된 최신값만 짧게 쓴다.',
      body: '- 배달정보는 주소, 건물명, 호수, 비밀번호를 분리해서 확인한다.\n- group_only 표기는 필요한 정보가 따로 있다는 뜻으로 남긴다.\n- 불명확하면 추정하지 말고 확인 경로를 남긴다.',
      tags: ['delivery', 'address', 'password', 'group_only'],
      search_text: '배달정보 조회 기준 주소 건물명 호수 비밀번호 group_only 최신값',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_delivery_lookup_rules'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123204000,
      updated_at_ms: 1783123204000,
      updated_at: '2026-07-04T00:00:04.000Z',
    },
    {
      id: 'seed_task_alarm_rules',
      category: 'task',
      title: '할일/알람 등록 기준',
      summary: '할일과 알람은 마감 시각, 반복 여부, 담당자를 같이 적는다.',
      body: '- 할일은 해야 할 일과 실행 기한을 한 번에 보이게 쓴다.\n- 알람은 반복 여부와 알림 시각을 분리해서 적는다.\n- 실행 주체가 필요한 경우 담당자나 방식을 같이 적는다.',
      tags: ['task', 'alarm', 'todo', 'deadline'],
      search_text: '할일 알람 등록 기준 마감 반복 담당자 todo reminder',
      source: OPS_MANUAL_SEED_SOURCE,
      sourceIds: ['seed_task_alarm_rules'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123205000,
      updated_at_ms: 1783123205000,
      updated_at: '2026-07-04T00:00:05.000Z',
    },
    {
      id: 'manual_baemin_customer_menu_change',
      category: 'customer_support',
      title: '배민 주문 메뉴 변경 안내',
      summary: '배달의민족 주문은 앱 상태를 먼저 보고, 안 되면 취소·재주문 또는 가맹점/고객센터 확인으로 안내한다.',
      body: '- 주문이 이미 들어갔는지 먼저 확인한다.\n- 배민 앱에서 취소나 변경이 가능한 상태인지 보고, 안 되면 취소 후 재주문을 안내한다.\n- 결제 후 직접 메뉴 수정을 확정하지 말고 앱 상태에 따라 고객센터나 가맹점 확인으로 넘긴다.\n- 매장 측에서는 메뉴 품절/숨김 관리 여부를 함께 확인해 같은 요청이 반복되지 않게 한다.',
      tags: ['customer_support', 'baemin', 'menu_change', 'customer'],
      search_text: '배민 주문 메뉴 변경 취소 재주문 고객센터 가맹점 메뉴 품절 숨김',
      source: OPS_MANUAL_SEED_SOURCE,
      source_urls: [
        'https://help.naver.com/service/30026/contents/20534?lang=ko',
        'https://ceo.baemin.com/guide/4268',
        'https://ceo.baemin.com/guide/4266'
      ],
      sourceIds: ['manual_baemin_customer_menu_change'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123206000,
      updated_at_ms: 1783123206000,
      updated_at: '2026-07-04T00:00:06.000Z',
    },
    {
      id: 'manual_coupangeats_customer_menu_change',
      category: 'customer_support',
      title: '쿠팡이츠 주문 메뉴 변경 안내',
      summary: '쿠팡이츠는 주문 수락 전후 상태를 먼저 확인하고, 수정이 어렵다면 취소 후 재주문과 매장 확인으로 안내한다.',
      body: '- 주문 수락 전이면 거절이나 취소 가능 여부를 먼저 확인한다.\n- 주문 수락 후 처리 중이면 직접 메뉴 수정보다 취소 가능 여부와 매장 확인을 우선한다.\n- 재고가 부족하면 품절 전환이 가능한지 보고, 메뉴 변경은 앱 상태에 따라 고객센터나 매장 확인으로 넘긴다.\n- 결제 후 메뉴를 바로 바꾼다고 단정하지 말고 주문 상태 기준으로 안내한다.',
      tags: ['customer_support', 'coupang_eats', 'menu_change', 'customer'],
      search_text: '쿠팡이츠 주문 메뉴 변경 주문 수락 전 거절 처리중 취소 재주문 품절 전환',
      source: OPS_MANUAL_SEED_SOURCE,
      source_urls: [
        'https://partners.coupangeats.com/start-guide/step-3/3530/',
        'https://partners.coupangeats.com/start-guide/step-2/4075/'
      ],
      sourceIds: ['manual_coupangeats_customer_menu_change'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123207000,
      updated_at_ms: 1783123207000,
      updated_at: '2026-07-04T00:00:07.000Z',
    },
    {
      id: 'manual_bbq_app_order_change',
      category: 'customer_support',
      title: 'BBQ 앱 주문 변경 안내',
      summary: 'BBQ 앱 주문은 완료 후 변경·취소를 콜센터 확인으로 안내한다.',
      body: '- 주문 완료 전이면 앱 상태를 먼저 확인한다.\n- 주문 완료 후 변경이나 취소는 공식 안내에 따라 콜센터 1588-9282 문의를 우선한다.\n- 제품 가격이나 메뉴 구성이 달라질 수 있으니, 앱 화면과 실제 주문 상태를 함께 보고 안내한다.\n- 매장 확인이 필요한 경우에도 주문 완료 상태를 먼저 기준으로 둔다.',
      tags: ['customer_support', 'bbq', 'menu_change', 'call_center'],
      search_text: 'BBQ 앱 주문 변경 취소 콜센터 1588-9282 제품 가격 메뉴 구성 변경',
      source: OPS_MANUAL_SEED_SOURCE,
      source_urls: [
        'https://bbq.co.kr/mypage/guide'
      ],
      sourceIds: ['manual_bbq_app_order_change'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123208000,
      updated_at_ms: 1783123208000,
      updated_at: '2026-07-04T00:00:08.000Z',
    },
    {
      id: 'manual_bbq_gifticon_menu_change',
      category: 'customer_support',
      title: 'BBQ 기프티콘 메뉴 변경 안내',
      summary: '기프티콘은 앱에서 쿠폰 등록 후 장바구니 메뉴 변경을 보고, 금액 조건은 앱 상태에 따라 확인한다.',
      body: '- 앱에서 쿠폰을 먼저 등록한다.\n- 장바구니에서 메뉴 변경 버튼이 보이는지 확인한다.\n- 쿠폰 금액 이상 메뉴 선택이나 추가 결제가 가능한지는 주문 화면과 앱 상태를 보고 판단한다.\n- 메뉴 변경이 애매하면 고객센터나 매장 확인으로 넘긴다.',
      tags: ['customer_support', 'bbq', 'gifticon', 'coupon', 'menu_change'],
      search_text: 'BBQ 기프티콘 메뉴 변경 쿠폰 등록 장바구니 메뉴 변경 쿠폰 금액 이상 추가 결제',
      source: OPS_MANUAL_SEED_SOURCE,
      source_urls: [
        'https://bbq.co.kr/mypage/guide',
        'https://cstarinfo.tistory.com/entry/%EB%B9%84%EB%B9%84%ED%81%90-BBQ-%EA%B8%B0%ED%94%84%ED%8B%B0%EC%BD%98-%EC%96%B4%ED%94%8C-%EC%A3%BC%EB%AC%B8-%EB%B0%A9%EB%B2%95-%EB%A9%94%EB%89%B4-%EB%B3%80%EA%B2%BD-%ED%99%A9%EA%B8%88%EC%98%AC%EB%A6%AC%EB%B8%8C-%ED%99%A9%EC%98%AC-%EB%B0%98%EB%B0%98'
      ],
      sourceIds: ['manual_bbq_gifticon_menu_change'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123209000,
      updated_at_ms: 1783123209000,
      updated_at: '2026-07-04T00:00:09.000Z',
    },
    {
      id: 'manual_platform_menu_change_staff_reply',
      category: 'platform_help',
      title: '메뉴 변경 문의 답변 기준',
      summary: '플랫폼별 주문 상태를 먼저 확인하고, 수정 단정 대신 취소·재주문·고객센터 안내로 답한다.',
      body: '- 고객이 메뉴 변경을 물으면 먼저 플랫폼과 주문 상태를 확인한다.\n- 배민과 쿠팡이츠는 결제 후 직접 메뉴 수정을 확정해서 말하지 말고 취소·재주문·고객센터/매장 확인 중심으로 답한다.\n- BBQ는 주문 완료 후 변경·취소를 콜센터 안내로 돌린다.\n- 기프티콘은 쿠폰 등록과 장바구니 메뉴 변경 가능 여부를 먼저 보고, 애매하면 확인 경로를 남긴다.',
      tags: ['platform_help', 'customer_support', 'menu_change', 'reply'],
      search_text: '메뉴 변경 문의 답변 기준 배민 쿠팡이츠 BBQ 기프티콘 취소 재주문 고객센터',
      source: OPS_MANUAL_SEED_SOURCE,
      source_urls: [
        'https://help.naver.com/service/30026/contents/20534?lang=ko',
        'https://ceo.baemin.com/guide/4268',
        'https://ceo.baemin.com/guide/4266',
        'https://partners.coupangeats.com/start-guide/step-3/3530/',
        'https://partners.coupangeats.com/start-guide/step-2/4075/',
        'https://bbq.co.kr/mypage/guide',
        'https://cstarinfo.tistory.com/entry/%EB%B9%84%EB%B9%84%ED%81%90-BBQ-%EA%B8%B0%ED%94%84%ED%8B%B0%EC%BD%98-%EC%96%B4%ED%94%8C-%EC%A3%BC%EB%AC%B8-%EB%B0%A9%EB%B2%95-%EB%A9%94%EB%89%B4-%EB%B3%80%EA%B2%BD-%ED%99%A9%EA%B8%88%EC%98%AC%EB%A6%AC%EB%B8%8C-%ED%99%A9%EC%98%AC-%EB%B0%98%EB%B0%98'
      ],
      sourceIds: ['manual_platform_menu_change_staff_reply'],
      sourceTypes: ['manual', OPS_MANUAL_SEED_SOURCE],
      status: 'active',
      updatedAt: 1783123210000,
      updated_at_ms: 1783123210000,
      updated_at: '2026-07-04T00:00:10.000Z',
    },
  ],
  memos: [],
};
